DEBUG = 0 
FINALPACKAGE = 1
ARCHS = armv7 arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = grouppy

grouppy_FILES = Tweak.x
grouppy_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
